config/routes.rb
Rails.application.routes.draw do
  get '/welcome' => 'welcome#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'accounts#new'
  post '/register' => 'accounts#create'

  resources :travels

  root 'welcome#index'
end

app/models/account.rb
class Account < ApplicationRecord
  has_secure_password
  belongs_to :user
  accepts_nested_attributes_for :user
  validates :email, uniqueness: true

  def self.authenticate(email, password)
    @account = Account.find_by(email: email) 
    if @account != nil && @account.authenticate(password)
      @account
    else
      nil
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user
  validates_presence_of :city_name
  validates_presence_of :travel_date
end

app/models/user.rb
class User < ApplicationRecord
  has_one :account
  has_many :travels
  validates :first_name, length: { minimum: 3 }
  validates :last_name, length: { minimum: 3 }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @account = Account.new
    @account.build_user
  end

  def create
    @account = Account.new(params_account)
  
    if @account.save
      redirect_to travels_path
    else
      render :new
    end
  end

  private

  def params_account
    params.require(:account).permit(:email, :password, :password_confirmation, user_attributes: [:id, :first_name, :last_name])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_login
    unless current_user
      flash[:alert] = "Please, log in"
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_login, only: [:destroy]

  def create
    if @account = Account.authenticate(params[:session][:email], params[:session][:password_digest])
      session[:user_id] = @account.user_id
      flash[:success] = 'You are log in!'
      redirect_to travels_path
    else
      flash[:alert] =  'You should have an account'
      redirect_to root_path
    end
  end

  def destroy
    session.destroy
    flash[:success] = 'You are log out!'
    redirect_to root_path
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :require_login
  
  def index
    @travels = current_user.travels
  end

  def show
    @travel = Travel.find(params[:id])
  end

  def new
    @travel = Travel.new
  end

  def create
    @travel = current_user.travels.build(params_travel)
   
    if @travel.save
      redirect_to @travel 
    else
      render :new
    end
  end

  def edit    
    @travel = Travel.find(params[:id])
  end

  def update
    @travel = Travel.find(params[:id])
    
    if @travel.update(params_travel)
      redirect_to @travel
    else
      render :edit
    end
  end

  def destroy
    @travel = Travel.find(params[:id])
    @travel.delete
    @travel.save

    redirect_to travels_path
  end

  helper_method :current_user

  private
  
  def params_travel
    params.require(:travel).permit(:city_name, :travel_date, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/new.html.haml
%h1 Add an account:
= form_for @account, url: { action: 'create' } do |f|
  %div
    = f.label :email
    = f.text_field :email
    =f.fields_for :user do |u|
      %div
        = u.label :first_name
        = u.text_field :first_name
      %div
        = u.label :last_name
        = u.text_field :last_name
  %div
    = f.label :password
    = f.password_field :password
  %div
    = f.label :password_confirmation
    = f.password_field :password_confirmation
    - if @account.errors.any?
      %div
        %h3 Please fix these errors:
        %ul
          - @account.errors.full_messages.each do |msg|
            %li= msg 
  = f.submit 'Create'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title TravelBlog
    = csrf_meta_tags
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", rel: "stylesheet"}/
  %body
    %nav.navbar.navbar-inverse
      %div.container-fluid
        %div.navbar-header
          = link_to 'Travel Blog', { action: 'index', controller: 'welcome' }, class: 'navbar-brand'
          %ul.nav.navbar-nav
            %li
              = link_to 'My travels', { action: 'index', controller: 'travels' }
            - if current_user.nil?
              %li
                = link_to 'Login', { action: 'new', controller: 'sessions' }
              %li
                = link_to 'Create an account', { action: 'new', controller: 'accounts' }
            - else
              %li
                = link_to 'Logout', { action: 'destroy', controller: 'sessions' }
    %div.container
      %div.jumbotron
        %div
          = render partial: 'sessions/flash_message.html.haml'
        = yield
    %div.navbar.navbar-default.navbar-fixed-bottom
      .container-fluid
        %p.navbar-text= "© 2018 Copyright:" 
        %a.navbar-text{ :href => "https://cool-beetles.github.io" } cool-beetles

app/views/travels/_form.html.haml
%div.controls
  %div.row
    %div.col-sm-5
      = f.label :city_name
      %br/
      = f.text_field :city_name
    %div.col-sm-5
      = f.label :travel_date
      %br/
      = f.date_field :travel_date
  %div.row
    %div.col-sm-10
      = f.label :description
      %br/
      = f.text_area :description, rows: :"10"

app/views/travels/edit.html.haml
%h1 Edit travel:
= form_for @travel do |f|
  = render partial: 'form', locals: { f: f }
  = f.submit "Edit"
- if @travel.errors.any?
  %h3 Please fix these errors:
  %ul
    - @travel.errors.full_messages.each do |msg|
      %li= msg

app/views/travels/index.html.haml
wheather add here 
%h1 List of Your travels:
- if @travels == nil
  %p There are not any travels currently in the system. Please, add Your memories.
- else
  %ul
    - @travels.each do |t|
      %li
        = link_to t.city_name, t
        = link_to t.travel_date, t
%div.btn-toolbar
  %div.btn-group-horizontal
    %p= link_to('Add new travel', new_travel_path, class: "btn btn-success")

app/views/travels/new.html.haml
%h1 Add new travel:
= form_for @travel do |f|
  = render partial: 'form', locals: { f: f }
  = f.submit "Create"
  - if @travel.errors.any?
    %div
      %h3 Please fix these errors:
      %ul
        - @travel.errors.full_messages.each do |msg|
          %li= msg
%p= link_to('Back', travels_path, class: "btn btn-success")

app/views/travels/show.html.haml
%h1
  = @travel.city_name
  = @travel.travel_date
%p
  %strong Description:
  = @travel.description
%hr/
%p= link_to 'Back', { action: 'index' }
%p= link_to 'Edit', { action: 'edit' }
%p= link_to 'Delete', @travel, method: :delete, data: { confirm: 'Are you sure?' }

app/views/welcome/index.html.haml
%h1 Welcome in Your personality Travel Blog!
%h3 Add description about Your travels, share ideas, spaces and informations!